# Generated by Django 3.1 on 2020-08-26 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20200826_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='Title',
            new_name='title',
        ),
    ]
