# Generated by Django 3.1 on 2020-08-27 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20200826_0430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
        migrations.RenameModel(
            old_name='Tutorials',
            new_name='Tutorial',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='tutorials',
            new_name='tutorial',
        ),
    ]
